services:
  docs:
    image: news_technology_example_local_docs
    container_name: news_technology_example_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./news_technology_example:/app/news_technology_example:z
    ports:
      - '9000:9000'
    command: /start-docs
